"""Stable error codes and the HTTP error envelope (§13.1)."""

from __future__ import annotations

from enum import Enum
from typing import Any


class ErrorCode(str, Enum):
    # request / auth
    VALIDATION_ERROR = "VALIDATION_ERROR"
    UNAUTHENTICATED = "UNAUTHENTICATED"
    FORBIDDEN = "FORBIDDEN"
    NOT_FOUND = "NOT_FOUND"
    CONFLICT = "CONFLICT"
    PAYLOAD_TOO_LARGE = "PAYLOAD_TOO_LARGE"
    SEMANTIC_ERROR = "SEMANTIC_ERROR"
    RATE_LIMITED = "RATE_LIMITED"
    DEPENDENCY_UNAVAILABLE = "DEPENDENCY_UNAVAILABLE"
    VERSION_CONFLICT = "VERSION_CONFLICT"
    IDEMPOTENCY_CONFLICT = "IDEMPOTENCY_CONFLICT"
    EVENT_CURSOR_EXPIRED = "EVENT_CURSOR_EXPIRED"

    # DSL / compiler (§4.3)
    CASE_TOO_LARGE = "CASE_TOO_LARGE"
    CASE_TITLE_REQUIRED = "CASE_TITLE_REQUIRED"
    CASE_STEPS_REQUIRED = "CASE_STEPS_REQUIRED"
    FRONT_MATTER_UNCLOSED = "FRONT_MATTER_UNCLOSED"
    FRONT_MATTER_INVALID = "FRONT_MATTER_INVALID"
    FRONT_MATTER_FIELD_UNKNOWN = "FRONT_MATTER_FIELD_UNKNOWN"
    DSL_VERSION_UNSUPPORTED = "DSL_VERSION_UNSUPPORTED"
    DSL_FENCE_INVALID = "DSL_FENCE_INVALID"
    DSL_FENCE_UNCLOSED = "DSL_FENCE_UNCLOSED"
    DSL_STEP_AMBIGUOUS = "DSL_STEP_AMBIGUOUS"
    DSL_AMBIGUOUS_SYNTAX = "DSL_AMBIGUOUS_SYNTAX"
    DSL_MISSING_FIELD = "DSL_MISSING_FIELD"
    DSL_FIELD_UNKNOWN = "DSL_FIELD_UNKNOWN"
    DSL_YAML_INVALID = "DSL_YAML_INVALID"
    DSL_YAML_TAG_FORBIDDEN = "DSL_YAML_TAG_FORBIDDEN"
    DSL_YAML_ALIAS_FORBIDDEN = "DSL_YAML_ALIAS_FORBIDDEN"
    DSL_YAML_TOO_DEEP = "DSL_YAML_TOO_DEEP"
    STEP_HEADING_INVALID = "STEP_HEADING_INVALID"
    STEP_NUMBER_DUPLICATED = "STEP_NUMBER_DUPLICATED"
    STEP_SEQUENCE_INVALID = "STEP_SEQUENCE_INVALID"
    STEP_EMPTY = "STEP_EMPTY"
    ACTION_UNSUPPORTED = "ACTION_UNSUPPORTED"
    TARGET_DESCRIPTION_REQUIRED = "TARGET_DESCRIPTION_REQUIRED"
    TARGET_NEEDS_LOCATOR = "TARGET_NEEDS_LOCATOR"
    TARGET_FIELD_UNKNOWN = "TARGET_FIELD_UNKNOWN"
    CONDITION_INVALID = "CONDITION_INVALID"
    CONDITION_UNSUPPORTED = "CONDITION_UNSUPPORTED"
    CONDITION_EXPECTED_REQUIRED = "CONDITION_EXPECTED_REQUIRED"
    CONDITION_FIELD_UNSUPPORTED = "CONDITION_FIELD_UNSUPPORTED"
    URL_REQUIRED = "URL_REQUIRED"
    WAIT_CONDITION_REQUIRED = "WAIT_CONDITION_REQUIRED"
    ATTACHMENT_REQUIRED = "ATTACHMENT_REQUIRED"
    SECRET_FIELD_NOT_ALLOWED = "SECRET_FIELD_NOT_ALLOWED"
    SECRET_TEMPLATE_NOT_ALLOWED = "SECRET_TEMPLATE_NOT_ALLOWED"
    VARIABLE_UNDECLARED = "VARIABLE_UNDECLARED"
    VARIABLE_TEMPLATE_INVALID = "VARIABLE_TEMPLATE_INVALID"
    VARIABLES_INVALID = "VARIABLES_INVALID"
    VARIABLE_DEFINITION_INVALID = "VARIABLE_DEFINITION_INVALID"
    DEFAULTS_INVALID = "DEFAULTS_INVALID"
    DEFAULT_TIMEOUT_INVALID = "DEFAULT_TIMEOUT_INVALID"
    STEP_TIMEOUT_INVALID = "STEP_TIMEOUT_INVALID"
    HUMAN_POLICY_INVALID = "HUMAN_POLICY_INVALID"
    IR_VALIDATION_FAILED = "IR_VALIDATION_FAILED"
    IR_VERSION_UNSUPPORTED = "IR_VERSION_UNSUPPORTED"
    AI_OUTPUT_INVALID = "AI_OUTPUT_INVALID"
    AI_UNAVAILABLE = "AI_UNAVAILABLE"
    AI_BUDGET_EXCEEDED = "AI_BUDGET_EXCEEDED"
    COMPILER_CAPABILITY_MISSING = "COMPILER_CAPABILITY_MISSING"

    # compile / execution gates
    COMPILE_FAILED = "COMPILE_FAILED"
    COMPILE_REVIEW_REQUIRED = "COMPILE_REVIEW_REQUIRED"
    COMPILE_STALE_DIGEST = "COMPILE_STALE_DIGEST"
    CASE_ARCHIVED = "CASE_ARCHIVED"
    ENVIRONMENT_REQUIRED = "ENVIRONMENT_REQUIRED"
    DOMAIN_NOT_ALLOWED = "DOMAIN_NOT_ALLOWED"
    VARIABLE_MISSING = "VARIABLE_MISSING"
    VARIABLE_TYPE_INVALID = "VARIABLE_TYPE_INVALID"
    SECRET_UNAVAILABLE = "SECRET_UNAVAILABLE"
    SECRET_VERSION_REVOKED = "SECRET_VERSION_REVOKED"
    ATTACHMENT_NOT_READY = "ATTACHMENT_NOT_READY"
    BROWSER_NOT_SUPPORTED = "BROWSER_NOT_SUPPORTED"
    QUOTA_EXCEEDED = "QUOTA_EXCEEDED"

    # runtime (§7, §8, §9)
    BROWSER_START_FAILED = "BROWSER_START_FAILED"
    BROWSER_CRASHED = "BROWSER_CRASHED"
    ACTION_OUTCOME_UNKNOWN = "ACTION_OUTCOME_UNKNOWN"
    ASSERTION_FAILED = "ASSERTION_FAILED"
    LOCATOR_NOT_FOUND = "LOCATOR_NOT_FOUND"
    LOCATOR_AMBIGUOUS = "LOCATOR_AMBIGUOUS"
    LOCATOR_NOT_INTERACTABLE = "LOCATOR_NOT_INTERACTABLE"
    EVIDENCE_CAPTURE_FAILED = "EVIDENCE_CAPTURE_FAILED"
    SESSION_LOST = "SESSION_LOST"
    STATE_STORE_UNAVAILABLE = "STATE_STORE_UNAVAILABLE"
    LEASE_LOST = "LEASE_LOST"
    CANCELLED = "CANCELLED"
    QUEUE_TIMEOUT = "QUEUE_TIMEOUT"
    ACTIVE_TIMEOUT = "ACTIVE_TIMEOUT"
    HUMAN_WAIT_TIMEOUT = "HUMAN_WAIT_TIMEOUT"
    HUMAN_TASK_TAKEN = "HUMAN_TASK_TAKEN"
    HUMAN_SESSION_LOST = "HUMAN_SESSION_LOST"
    EGRESS_BLOCKED = "EGRESS_BLOCKED"
    TARGET_HTTP_ERROR = "TARGET_HTTP_ERROR"
    STEP_NOT_FOUND = "STEP_NOT_FOUND"
    EXECUTION_NOT_RUNNABLE = "EXECUTION_NOT_RUNNABLE"
    UNSUPPORTED_TARGET_SCOPE = "UNSUPPORTED_TARGET_SCOPE"
    UNEXPECTED_DIALOG = "UNEXPECTED_DIALOG"
    ANALYSIS_FAILED = "ANALYSIS_FAILED"


STATUS_FOR_CODE: dict[ErrorCode, int] = {
    ErrorCode.VALIDATION_ERROR: 400,
    ErrorCode.UNAUTHENTICATED: 401,
    ErrorCode.FORBIDDEN: 403,
    ErrorCode.NOT_FOUND: 404,
    ErrorCode.CONFLICT: 409,
    ErrorCode.VERSION_CONFLICT: 409,
    ErrorCode.IDEMPOTENCY_CONFLICT: 409,
    ErrorCode.COMPILE_REVIEW_REQUIRED: 409,
    ErrorCode.COMPILE_STALE_DIGEST: 409,
    ErrorCode.COMPILE_FAILED: 409,
    ErrorCode.CASE_ARCHIVED: 409,
    ErrorCode.HUMAN_TASK_TAKEN: 409,
    ErrorCode.HUMAN_WAIT_TIMEOUT: 409,
    ErrorCode.ATTACHMENT_NOT_READY: 409,
    ErrorCode.EXECUTION_NOT_RUNNABLE: 409,
    ErrorCode.SECRET_VERSION_REVOKED: 409,
    # §13.1: 413 is a size limit, 422 is syntax or semantics, and 409 is reserved for state conflicts.
    ErrorCode.PAYLOAD_TOO_LARGE: 413,
    ErrorCode.CASE_TOO_LARGE: 413,
    ErrorCode.SEMANTIC_ERROR: 422,
    ErrorCode.VARIABLE_MISSING: 422,
    ErrorCode.VARIABLE_TYPE_INVALID: 422,
    ErrorCode.BROWSER_NOT_SUPPORTED: 422,
    ErrorCode.DOMAIN_NOT_ALLOWED: 422,
    ErrorCode.ENVIRONMENT_REQUIRED: 422,
    ErrorCode.RATE_LIMITED: 429,
    ErrorCode.QUOTA_EXCEEDED: 429,
    ErrorCode.AI_BUDGET_EXCEEDED: 429,
    ErrorCode.DEPENDENCY_UNAVAILABLE: 503,
    ErrorCode.AI_UNAVAILABLE: 503,
    ErrorCode.SECRET_UNAVAILABLE: 503,
    ErrorCode.STATE_STORE_UNAVAILABLE: 503,
}

DSL_CODES = {
    ErrorCode.CASE_TOO_LARGE,
    ErrorCode.CASE_TITLE_REQUIRED,
    ErrorCode.CASE_STEPS_REQUIRED,
    ErrorCode.FRONT_MATTER_UNCLOSED,
    ErrorCode.FRONT_MATTER_INVALID,
    ErrorCode.FRONT_MATTER_FIELD_UNKNOWN,
    ErrorCode.DSL_VERSION_UNSUPPORTED,
    ErrorCode.DSL_FENCE_INVALID,
    ErrorCode.DSL_FENCE_UNCLOSED,
    ErrorCode.DSL_STEP_AMBIGUOUS,
    ErrorCode.DSL_AMBIGUOUS_SYNTAX,
    ErrorCode.DSL_MISSING_FIELD,
    ErrorCode.DSL_FIELD_UNKNOWN,
    ErrorCode.DSL_YAML_INVALID,
    ErrorCode.DSL_YAML_TAG_FORBIDDEN,
    ErrorCode.DSL_YAML_ALIAS_FORBIDDEN,
    ErrorCode.DSL_YAML_TOO_DEEP,
    ErrorCode.STEP_HEADING_INVALID,
    ErrorCode.STEP_NUMBER_DUPLICATED,
    ErrorCode.STEP_SEQUENCE_INVALID,
    ErrorCode.STEP_EMPTY,
    ErrorCode.ACTION_UNSUPPORTED,
    ErrorCode.TARGET_DESCRIPTION_REQUIRED,
    ErrorCode.TARGET_FIELD_UNKNOWN,
    ErrorCode.CONDITION_INVALID,
    ErrorCode.CONDITION_UNSUPPORTED,
    ErrorCode.CONDITION_EXPECTED_REQUIRED,
    ErrorCode.CONDITION_FIELD_UNSUPPORTED,
    ErrorCode.URL_REQUIRED,
    ErrorCode.WAIT_CONDITION_REQUIRED,
    ErrorCode.ATTACHMENT_REQUIRED,
    ErrorCode.SECRET_FIELD_NOT_ALLOWED,
    ErrorCode.SECRET_TEMPLATE_NOT_ALLOWED,
    ErrorCode.VARIABLE_UNDECLARED,
    ErrorCode.VARIABLE_TEMPLATE_INVALID,
    ErrorCode.VARIABLES_INVALID,
    ErrorCode.VARIABLE_DEFINITION_INVALID,
    ErrorCode.DEFAULTS_INVALID,
    ErrorCode.DEFAULT_TIMEOUT_INVALID,
    ErrorCode.STEP_TIMEOUT_INVALID,
    ErrorCode.HUMAN_POLICY_INVALID,
    ErrorCode.IR_VALIDATION_FAILED,
    ErrorCode.TARGET_NEEDS_LOCATOR,
    ErrorCode.AI_OUTPUT_INVALID,
    ErrorCode.COMPILER_CAPABILITY_MISSING,
}


class ApiError(Exception):
    """Raise from services and routes; rendered by the exception handler (§13.1)."""

    def __init__(
        self,
        code: ErrorCode | str,
        message: str,
        *,
        http_status: int | None = None,
        details: dict[str, Any] | None = None,
    ) -> None:
        self.code = ErrorCode(code) if not isinstance(code, ErrorCode) else code
        self.message = message
        self.details = details or {}
        self.http_status = http_status or STATUS_FOR_CODE.get(self.code, 422 if self.code in DSL_CODES else 400)
        super().__init__(message)

    def as_envelope(self, request_id: str | None = None) -> dict[str, Any]:
        error: dict[str, Any] = {"code": self.code.value, "message": self.message}
        if request_id:
            error["request_id"] = request_id
        if self.details:
            error["details"] = self.details
        return {"error": error}
